#!/usr/bin/env python3
"""Convert a Teams .vtt caption export into a cleaned, speaker-turn transcript.

Strips WEBVTT headers, cue IDs (e.g. 45211125-391e-4a58-a74c-58f7b66e9b05/9-1),
and per-cue timestamp ranges. Merges consecutive cues from the same speaker into
one turn, keeping only the timestamp of when that turn started. Text is kept
verbatim (no paraphrasing, filler words included).

Usage:
    vtt_to_txt.py <input.vtt> <output.txt> --source-name <original filename> \
        [--generated-by "Full Name"] [--generated-on "YYYY-MM-DD"]

If --generated-on is omitted, today's date is used. If --generated-by is
omitted, "Daniel Macuare" is used.
"""
import argparse
import re
from datetime import date

CUE_TEXT_RE = re.compile(r"<v\s+([^>]+)>(.*?)</v>", re.DOTALL)
TIMESTAMP_RE = re.compile(r"(\d{2}:\d{2}:\d{2})\.\d+\s*-->")


def parse_vtt(content: str):
    """Yield (start_time, speaker, text) turns, merging consecutive same-speaker cues."""
    turns = []
    current_speaker = None
    current_start = None
    current_parts = []

    for block in content.split("\n\n"):
        lines = block.strip("\n").split("\n")
        if not lines or lines[0].strip() in ("", "WEBVTT"):
            continue

        ts_idx, start_time = None, None
        for i, line in enumerate(lines):
            m = TIMESTAMP_RE.search(line)
            if m:
                ts_idx, start_time = i, m.group(1)
                break
        if ts_idx is None:
            continue

        m = CUE_TEXT_RE.search("\n".join(lines[ts_idx + 1:]))
        if not m:
            continue

        speaker = m.group(1).strip()
        text = re.sub(r"\s+", " ", m.group(2).replace("\n", " ")).strip()
        if not text:
            continue

        if speaker == current_speaker:
            current_parts.append(text)
        else:
            if current_speaker is not None:
                turns.append((current_start, current_speaker, " ".join(current_parts)))
            current_speaker, current_start, current_parts = speaker, start_time, [text]

    if current_speaker is not None:
        turns.append((current_start, current_speaker, " ".join(current_parts)))
    return turns


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_vtt")
    parser.add_argument("output_txt")
    parser.add_argument("--source-name", default=None,
                         help="Original filename to record in the header (defaults to the input filename)")
    parser.add_argument("--generated-by", default="Daniel Macuare")
    parser.add_argument("--generated-on", default=None,
                         help="Defaults to today's date (YYYY-MM-DD)")
    args = parser.parse_args()

    with open(args.input_vtt, encoding="utf-8") as f:
        content = f.read()

    turns = parse_vtt(content)

    source_name = args.source_name or args.input_vtt.rsplit("/", 1)[-1]
    generated_on = args.generated_on or date.today().isoformat()

    with open(args.output_txt, "w", encoding="utf-8") as f:
        f.write(f"File generated by AI from the source document: {source_name}\n")
        f.write(f"Generated on: {generated_on}\n")
        f.write(f"Generated by: {args.generated_by}\n\n")
        for start_time, speaker, text in turns:
            f.write(f"[{start_time}] {speaker}: {text}\n\n")

    print(f"Wrote {len(turns)} turns to {args.output_txt}")


if __name__ == "__main__":
    main()
